# config.yaml
# Î»
sources: "/Users/omichel/Desktop/qilimanjaro/projects/quantum_transport/quantum_state_transfer/src"

experiment:
  name: "error_analysis_z"
  description: "Z error analysis for N=13 system"
  output_dir: "../../files/okr_error_data/error_files/figures/local"
  input_file: '../../files/okr_error_data/error_files/errors/z_err_N13_50_points_50_shots.npz'
  run_simulation: False # Set to false to only plot existing data
  
system:
  N: 13
  lambda: 0.02272
  J: 0.5 
  state_dictionary: {"1": 1}
  
simulation:
  ti: 0
  Nsteps: 500
  Nshots: 50
  
errors:
  j_error_range:
    lower: 0.001
    upper: 0.01
    num_points: 50
  l_error_range:
    lower: 0.01
    upper: 0.1
    num_points: 50
  z_error_range:
    lower: 0.001
    upper: 0.004
    num_points: 50
  error_type: "z"  # "j", "l", or "z"
  
plotting:
  title: "Fidelity vs. Z error"
  xlabel: "Error (MHz)"
  save_figures: True